import React, { useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { ArrowRight, Check, ChevronRight, Clock3, MapPin, Menu, Search, ShoppingBag, Sparkles, X } from 'lucide-react'
import { filterVenues, offers, themes } from './data'
import './styles.css'

const Badge = ({ children, kind = '' }) => <span className={`badge ${kind}`}>{children}</span>
function VenueCard({ venue, onOpen }) {
  return <article className="venue-card">
    <div className="venue-image" style={{ background: venue.colour }}><span>{venue.image}</span><Badge kind={venue.status === 'REFERENCE' ? 'reference' : 'demo'}>{venue.status === 'REFERENCE' ? 'REFERENCE DATA' : 'DEMO / TEST DATA'}</Badge></div>
    <div className="venue-content"><div className="card-heading"><div><p className="eyebrow">{venue.location} · {venue.cuisine.join(' / ')}</p><h3>{venue.name}</h3></div><span className="price">{venue.price}</span></div>
    <p>{venue.description}</p><div className="chips">{venue.facilities.slice(0, 3).map(f => <span key={f}>{f}</span>)}</div>
    {venue.status === 'REFERENCE' && <p className="reference-copy">Reference menu • not a MARIBON partner</p>}
    <button className="text-button" onClick={() => onOpen(venue)}>View venue <ArrowRight size={16}/></button></div>
  </article>
}
function VenuePanel({ venue, close, add }) {
  if (!venue) return null
  return <div className="modal-backdrop" role="presentation"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="venue-title"><button className="close" onClick={close} aria-label="Close venue"><X /></button><div className="modal-banner" style={{background: venue.colour}}>{venue.image}</div><Badge kind={venue.status === 'REFERENCE' ? 'reference' : 'demo'}>{venue.status === 'REFERENCE' ? 'REFERENCE DATA · NOT A PARTNER' : 'APPROVED MARIBON PARTNER · DEMO'}</Badge><h2 id="venue-title">{venue.name}</h2><p>{venue.description}</p><div className="details"><span><MapPin/> {venue.location}</span><span><Clock3/> {venue.prep}</span></div>
  {venue.status === 'REFERENCE' && <div className="notice"><strong>Reference menu • not a MARIBON partner</strong><br/>Prices and availability must be confirmed by the business. MARIBON ordering is disabled.</div>}
  <h3>Menu</h3>{venue.menu.map(item => <div className="menu-item" key={item.name}><div><strong>{item.name}</strong><p>{item.description}</p><small>{item.prep ? `${item.prep} min` : 'Partner price required'}</small></div><div className="menu-action">{item.price ? <><b>Rs {item.price}</b><button onClick={() => add(item, venue)}>Add</button></> : <><b>Price to verify</b><button disabled>Unavailable</button></>}</div></div>)}
  <p className="fulfilment">Ordering model: <strong>{venue.ordering.replace('_', ' ')}</strong>. The venue fulfils its own orders.</p></section></div>
}
function App() {
 const [menuOpen,setMenuOpen]=useState(false), [query,setQuery]=useState(''), [location,setLocation]=useState('All'), [theme,setTheme]=useState('All'), [delivery,setDelivery]=useState(false), [active,setActive]=useState(null), [cart,setCart]=useState([]), [notice,setNotice]=useState('')
 const results=useMemo(()=>filterVenues({query,location,theme,delivery}),[query,location,theme,delivery])
 const add=(item,venue)=>{setCart(c=>[...c,{...item,venue:venue.name}]);setNotice(`${item.name} added to your demo basket`);setTimeout(()=>setNotice(''),3000)}
 const scroll=(id)=>document.getElementById(id)?.scrollIntoView({behavior:'smooth'})
 return <><header><a className="brand" href="#top" aria-label="MARIBON HUB home"><i></i><span>MARIBON<em> HUB</em></span></a><nav className={menuOpen?'open':''}>{['Home','Explore','Food Themes','Venues','Offers','Reviews','Rewards'].map(x=><a key={x} href={`#${x === 'Home'?'top':x.toLowerCase().replace(' ','-')}`} onClick={()=>setMenuOpen(false)}>{x}</a>)}<a className="business" href="#business">For businesses</a></nav><div className="header-actions"><button className="basket" onClick={()=>scroll('basket')} aria-label="Open basket"><ShoppingBag size={18}/><b>{cart.length}</b></button><button className="menu-toggle" onClick={()=>setMenuOpen(!menuOpen)} aria-label="Toggle navigation"><Menu/></button></div></header>
 <main id="top"><section className="hero"><div className="hero-copy"><p className="pilot"><span></span> Saint Pierre → Moka pilot</p><h1>Discover Mauritius<br/><mark>through its food.</mark></h1><p className="tagline">Moris <b>•</b> Manze <b>•</b> Lasanble</p><p className="intro">Restaurants, menus, food experiences, offers, community reviews and delivery options — gathered in one local food destination.</p><div className="hero-buttons"><button className="primary" onClick={()=>scroll('explore')}>Explore food <ArrowRight size={18}/></button><button className="secondary" onClick={()=>scroll('venues')}>Find a venue</button></div><a href="#business" className="business-link">Building a food business? <b>Join MARIBON</b><ChevronRight size={16}/></a></div><div className="hero-art" aria-label="Illustration of Mauritian food discovery"><div className="sun"></div><div className="plate">🍲</div><div className="float-card a">🔥 <b>Local favourites</b></div><div className="float-card b">📍 <b>Moka & Saint Pierre</b></div><div className="palm">✦</div></div></section>
 <section className="trust"><span>YOUR LOCAL FOOD ECOSYSTEM</span><span>DISCOVER WITH CARE</span><span>BUILT FOR MAURITIUS</span><span>GROWING TOGETHER</span></section>
 <section id="food-themes" className="section"><div className="section-head"><div><p className="eyebrow">CHOOSE YOUR MOOD</p><h2>Food, by feeling.</h2></div><p>Our themes are discovery lanes, not rigid cuisines. One dish can belong to more than one.</p></div><div className="themes">{themes.map(t=><button className={`theme ${t.tone}`} onClick={()=>{setTheme(t.id);scroll('explore')}} key={t.id}><span className="theme-icon">{t.icon}</span><div><small>{t.time}</small><h3>{t.name}</h3><p>{t.line}</p></div><ArrowRight/></button>)}</div></section>
 <section id="explore" className="explore section"><div className="section-head"><div><p className="eyebrow">EXPLORE THE PILOT</p><h2>Your next good meal.</h2></div><p>Search venues, dishes, themes and localities. Demo and reference information is always clearly labelled.</p></div><div className="search-bar"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Try “chicken”, “pizza” or “Moka”" aria-label="Search venues and food"/><button>Search</button></div><div className="filters"><label>Location<select value={location} onChange={e=>setLocation(e.target.value)}><option>All</option><option>Moka</option><option>Saint Pierre</option></select></label><label>Food theme<select value={theme} onChange={e=>setTheme(e.target.value)}><option value="All">All themes</option>{themes.map(t=><option value={t.id} key={t.id}>{t.name}</option>)}</select></label><label className="check"><input checked={delivery} onChange={e=>setDelivery(e.target.checked)} type="checkbox"/> Delivery available</label></div><p className="result-count">{results.length} venue{results.length!==1?'s':''} matching your discovery</p><div className="venue-grid">{results.map(v=><VenueCard key={v.id} venue={v} onOpen={setActive}/>)}</div></section>
 <section id="offers" className="offers section"><div className="section-head"><div><p className="eyebrow">MARIBON MOMENTS</p><h2>Offers with context.</h2></div></div><div className="offer-grid">{offers.map(o=><article className="offer" style={{borderTopColor:o.colour}} key={o.title}><Badge>{o.type}</Badge><h3>{o.title}</h3><p>{o.copy}</p><a href="#business">Learn more <ArrowRight size={15}/></a></article>)}</div></section>
 <section id="business" className="business-section"><div><p className="eyebrow">FOR BUSINESSES</p><h2>Your food deserves a better front door.</h2><p>Apply to become an approved MARIBON partner. Submit your details, sign your declaration, then keep your menus and ordering setup in your hands.</p></div><div className="steps"><span><b>1</b> Apply</span><span><b>2</b> Admin review</span><span><b>3</b> Publish</span><button className="primary">Start application <ArrowRight size={18}/></button></div></section>
 <section id="basket" className="basket-section section"><p className="eyebrow">YOUR BASKET</p><h2>{cart.length ? `${cart.length} demo item${cart.length > 1 ? 's' : ''} ready` : 'Your basket is waiting.'}</h2>{cart.length ? <><ul>{cart.map((x,i)=><li key={`${x.name}${i}`}><span>{x.name}<small>{x.venue}</small></span><b>Rs {x.price}</b></li>)}</ul><p className="notice">Demo checkout only. Production orders must be created server-side with verified prices, payment and identity.</p></>:<p>Add an available demo menu item to preview the MARIBON basket journey.</p>}</section>
 </main><footer><div className="brand"><i></i><span>MARIBON<em> HUB</em></span></div><p>Moris • Manze • Lasanble</p><div><a href="#top">Privacy</a><a href="#top">Terms</a><a href="#business">Supplier terms</a></div></footer>{active&&<VenuePanel venue={active} close={()=>setActive(null)} add={add}/>} {notice&&<div role="status" className="toast"><Check size={16}/>{notice}</div>}</>
}
createRoot(document.getElementById('root')).render(<App />)
